### ISSUE TITLE
SwiftPoet Status

### ISSUE THREAD

**Issue by oldergod** [outfoxx/swiftpoet#87]
Hello!

At Wire https://github.com/square/wire we rely heavily on SwiftPoet and we’re a bit anxious about the project’s state and its future. Would you be open to add one or two of us to it so we can make changes, fix bugs, and make some releases? Is SwiftPoet still getting support from you or someone else?
Worst case scenario for us would be to fork the project. We'd love to hear back from you; we're totally up to helping the project is possible.
Let us know

**Comment by kdubb** [comment]
Absolutely! Would love the help!

**Comment by dnkoutso** [comment]
@kdubb would love to start with this https://github.com/outfoxx/swiftpoet/pull/86

also we identified more issues that are probably fixed in Kotlin Poet....seems like a large update required...I could give it a shot but was hoping for some help as well.

**Comment by dnkoutso** [comment]
@kdubb would love to start with this https://github.com/outfoxx/swiftpoet/pull/86

also we identified more issues that are probably fixed in Kotlin Poet....seems like a large update required...I could give it a shot but was hoping for some help as well.

**Comment by kdubb** [comment]
The biggest issue holding things back is when I switched to SonarCloud originally I didn't realize the issues with external PR's.

**Comment by kdubb** [comment]
I have fixed workflows I can adapt from our other repositories.

**Comment by dnkoutso** [comment]
Thank you @kdubb ! We had identified another issue and we had fixed it at the Wire level...its possible this can be fixed to SwiftPoet as it seems some new logic was added into KotlinPoet to deal with this.

https://github.com/square/wire/pull/2658

In particular I think we are missing logic like this https://github.com/square/kotlinpoet/blob/main/kotlinpoet/src/main/java/com/squareup/kotlinpoet/CodeWriter.kt#L432 within CodeWriter.kt...

It turns out in some cases if we can resolve the type name we do not store that as an import to keep for the second pass to actually write the correct imports...

I have started trying to accomplish that in SwiftPoet and the Wire PR above has a test case that verifies the issue...

**Comment by kdubb** [comment]
@dnkoutso I'm unsure of exactly what you are wanting. Can you make a PR? Or at least a PR with a failing test case?

**Comment by kdubb** [comment]
@oldergod Who should be added to the team?

**Comment by oldergod** [comment]
@dnkoutso and myself @oldergod would be great! Thank you

**Comment by kdubb** [comment]
@oldergod I've invited you both to the team! Welcome! I'm happy to have help maintaining and updating the library!

I would only ask that you guys keep me in the loop via review requests as we begin working together.

**Comment by oldergod** [comment]
> I would only ask that you guys keep me in the loop via review requests as we begin working together.

Of course!

**Comment by oldergod** [comment]
@kdubb Hey Kevin, we cannot merge PRs for we're not authorised to do so.

![image](https://github.com/outfoxx/swiftpoet/assets/1767669/c787f749-3b78-4175-aeb3-08e35e187bbd)

Did you mean to keep reviewing things and merging them yourself?

**Comment by kdubb** [comment]
@oldergod Nope, I thought you were able to do so.

**Comment by oldergod** [comment]
Thanks @kdubb would you mind sending an email to bquenaudon@squareup.com ? I tried info@outfoxx.io but doesn't exist anymore?

**Comment by dnkoutso** [comment]
I think we should close this?

**Comment by oldergod** [comment]
🚀
